// The DeepSeek-V4-Flash prompt renderer's differential gate: our
// Dsv4Prompt::render + tokenizer vs the goldens the checkpoint's own
// encoder produced (tests/data/dsv4_prompt_goldens.jsonl, generated by
// tools/gen_dsv4_prompt_goldens.py). Each case checks the byte-exact
// render AND the tokenizer ids of that render — the render -> tokenizer
// integration the service path uses. The corpus header cross-references
// the tokenizer.json's FNV-1a-64; a different tokenizer.json refuses the
// run. The tokenizer loads from the local model dir (DGPP_DSV4_MODEL_DIR,
// default /data/models/DeepSeek-V4-Flash-0731) — this checkpoint is not
// in the HF hub cache.
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "common/log.hpp"

int g_argc = 0;
char** g_argv = nullptr;
#include "common/test.hpp"
#include "loaders/minijson.hpp"
#include "text/dsv4_prompt.hpp"
#include "text/tokenizer.hpp"

namespace {

std::string golden_path(int argc, char** argv) {
  return argc > 1 ? argv[1] : "tests/data/dsv4_prompt_goldens.jsonl";
}

std::string model_dir() {
  if (const char* env = std::getenv("DGPP_DSV4_MODEL_DIR"); env && *env) return env;
  return "/data/models/DeepSeek-V4-Flash-0731";
}

void require(bool cond, const std::string& what) {
  if (!cond) throw std::runtime_error(what);
}

std::string read_text_file(const std::string& path) {
  std::ifstream f(path);
  if (!f) throw std::runtime_error("cannot open " + path);
  std::ostringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

std::string escaped(const std::string& s, size_t limit = 400) {
  std::string out;
  for (size_t i = 0; i < s.size() && i < limit; ++i) {
    const char c = s[i];
    if (c == '\n') out += "\\n";
    else if (c == '\r') out += "\\r";
    else out += c;
  }
  if (s.size() > limit) out += "...";
  return out;
}

}  // namespace

DGPP_TEST(dsv4_prompt_differential_goldens) {
  const std::string kGoldenPath = golden_path(g_argc, g_argv);
  const std::vector<std::string> lines = [&] {
    std::vector<std::string> out;
    std::istringstream f(read_text_file(kGoldenPath));
    std::string line;
    while (std::getline(f, line))
      if (!line.empty()) out.push_back(line);
    return out;
  }();
  require(lines.size() >= 2, "golden corpus is empty");
  const dgpp::minijson::ParseResult hp = dgpp::minijson::parse(lines[0]);
  const dgpp::minijson::Value& header = hp.root;

  const std::string mdir = model_dir();
  const std::filesystem::path tok_path = std::filesystem::path(mdir) / "tokenizer.json";
  if (!std::filesystem::exists(tok_path)) {
    DGPP_LOG_WARN("dsv4_prompt_test: {} not found; skipping (set DGPP_DSV4_MODEL_DIR)",
                  tok_path.string());
    std::exit(2);
  }
  const dgpp::text::Tokenizer tok = dgpp::text::Tokenizer::load(tok_path.string());
  {
    char got[32];
    std::snprintf(got, sizeof(got), "%016llx", static_cast<unsigned long long>(tok.revision_hash()));
    require(std::string(header.at("tokenizer_hash").as_string()) == got,
            "golden tokenizer_hash does not match this tokenizer.json — regenerate the goldens "
            "(tools/gen_dsv4_prompt_goldens.py)");
  }
  size_t checked = 0;
  for (size_t i = 1; i < lines.size(); ++i) {
    const dgpp::minijson::ParseResult parsed = dgpp::minijson::parse(lines[i]);
    const dgpp::minijson::Value& rec = parsed.root;
    const std::string name(rec.at("name").as_string());
    const dgpp::minijson::Value& kwargs = rec.at("kwargs");
    const std::string want(rec.at("render").as_string());
    const std::string rendered = [&] {
      try {
        return dgpp::text::Dsv4Prompt::render(kwargs);
      } catch (const std::exception& e) {
        throw std::runtime_error("case '" + name + "': " + e.what());
      }
    }();
    if (rendered != want) {
      size_t k = 0;
      while (k < rendered.size() && k < want.size() && rendered[k] == want[k]) ++k;
      std::printf("[FAIL] case '%s' differs at byte %zu\n  got:  %s\n  want: %s\n", name.c_str(), k,
                  escaped(rendered.substr(k > 40 ? k - 40 : 0)).c_str(),
                  escaped(want.substr(k > 40 ? k - 40 : 0)).c_str());
      require(false, "case '" + name + "': render differs from the reference encoder's");
    }
    std::vector<int64_t> want_ids;
    for (const auto& v : rec.at("ids").items()) want_ids.push_back(v.as_int());
    const std::vector<int64_t> got_ids = tok.encode(rendered);
    require(got_ids == want_ids, "case '" + name + "': the render's ids differ from the reference tokenizer's");
    ++checked;
  }
  DGPP_LOG_INFO("dsv4 prompt differential: {}/{} cases byte-exact with matching ids", checked,
                lines.size() - 1);
}

int main(int argc, char** argv) {
  g_argc = argc;
  g_argv = argv;
  return dgpp::test::run_all();
}
